	<div id="content">
	<div id="single">
		<table border="0">
		<FORM METHOD="POST" ACTION="?l=dataprocessorlogin.php">
		<tr>
			<td>Username</td>
			<td><INPUT TYPE="text" NAME="username" size=53 MAXLENGTH="36"></td>
		</tr>
		
		<tr>
			<td>Password</td>
			<td><INPUT TYPE="password" NAME="pass" size=53 </td>
		</tr>

		<tr>
			<td>
				<INPUT TYPE="submit" VALUE="login"> <INPUT TYPE="reset">
			</td>
		</tr>
		<tr>
		<td>
		Belum Punya Akun?
		</td>
		<td><a href="?l=formregister.inc"><input type="button" name="register" value="Daftar Sekarang"></a>
		</td>
		</tr>
		</FORM>
		</table>
	</div>
</div>
