<div id="contentkontak">
    <div id="singlekontak">
        <h2>Kontak</h2> 
        <p style="color:white;text-align: center;margin:2px;font-size:20px;"> Selamat datang di Web Toko Buku Sukses Jaya Utama. Toko buku ini memuat buku tentang pemrograman. Pertanyaan berkaitan dengan informasi tentang toko ini dapat menghubungi kontak dibawah ini.</p>
        <br>
        <table>
            <tr>
                <td>No Telp</td>
                <td>:</td>
                <td style="color:white;font-size:20px;">+62 81234567890</td>
            </tr>
            <tr>
                <td>Nama Toko</td>
                <td>:</td>
                <td style="color:white;font-size:20px;">PT. Toko Buku Sukses Jaya Utama</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>:</td>
                <td style="color:white;font-size:20px;">tokobukusukses@mail.com</td>
            </tr>
        </table>
        <center><img src="gambar/logo.png" width="150px" height="150px"></center>
    </div>
</div>